name: Team awesome's approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    name: Label wehn approved
    runs-on: ubuntu-latest
    steps: 
    - name: Label when approved
      uses: pullreminders/label-when-approved-action@master
      env:
        APPROVALS: "1"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # GITHUB_TOKEN is necessary so the action can create and apply labels to this repository. See the action's documentation for how to use it
        ADD_LABEL: "approved"
        # The name of the label which should be added when the number of approvals have been met, choose any label name you wish
    
